### ISSUE TITLE
Backdrop Texture Missing

### ISSUE THREAD

**Issue by Bugsbugme** [SFX-WoW/Masque_Caith#3]
I just updated and the backdrop texture no longer shows up using the classic version.
I've reinstalled both Caith and the main Masque addon, but still not working.

**Comment by StormFX** [comment]
_Caith_ now uses a solid color instead of a texture until I come up with something better.

**Comment by StormFX** [comment]
To clarify: This is not a bug. I removed the Backdrop texture because it was dated and didn't fit with _Caith_'s style. I'm working on a new set of Backdrop textures. There will be different textures for Action, Item and Pet buttons.

**Comment by StormFX** [comment]
Fixed @ 5b2214f.
