### ISSUE TITLE
Transmogrifier drop down set list not working

### ISSUE THREAD

**Issue by 3Dxirtam** [SFX-WoW/Masque_Caith#6]
When enable Masque: Caith plugin transmogrifier set list isn't expanding.

**Comment by StormFX** [comment]
Masque: Caith doesn't affect the transmogrifier UI.

**Comment by 3Dxirtam** [comment]
I think this is an indirect bug.
A friend confirm same issue:
- Masque enabled no problem
- Masque Caith enabled transmogrifier set list isn't expanding.
For information "FR" client

**Comment by StormFX** [comment]
I'll see if there's a typo in the frFR file.
